"""Event-aligned extraction for soma calcium-imaging traces.

This module reads processed soma calcium traces from a SummaryLoCo MAT file,
reconstructs continuous per-DMD session traces, aligns them to corrected Bonsai
stimulus events, and writes mean, single-trial, and sequence-aligned calcium
packages to ``analysis/derived/calcium``.

The extraction pathway mirrors the glutamate event-alignment outputs where
possible, but operates on manually exported soma ROIs and can optionally apply
soma-QC masks generated by :mod:`vip_slap2_analysis.calcium.qc`.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import numpy as np

from vip_slap2_analysis.common.session import SessionAssets
from vip_slap2_analysis.common.alignment import (
    EventWindows,
    align_traces_to_session_intervals,
    build_change_locked_sequences,
    extract_change_intervals,
    extract_image_intervals,
    extract_omission_intervals,
    extract_ordered_change_targets,
    filter_intervals_to_epochs,
    filter_ordered_images_to_epochs,
    load_corrected_bonsai_csv,
    load_imaging_epochs_csv,
    summarize_event_tensor,
    tolerant_summary_ragged,
)
from vip_slap2_analysis.glutamate.summary import GlutamateSummary


def _resolve_im_rate_hz(asset: SessionAssets, metadata: Dict[str, Any]) -> float:
    """Resolve the imaging sampling rate for calcium extraction.

    The lookup order is caller metadata followed by session-asset metadata. Both
    ``im_rate_hz`` and ``im_rate_Hz`` spellings are accepted.

    Returns
    -------
    float
        Imaging rate in hertz.

    Raises
    ------
    ValueError
        If no imaging-rate field can be found.
    """
    if "im_rate_hz" in metadata:
        return float(metadata["im_rate_hz"])
    if "im_rate_Hz" in metadata:
        return float(metadata["im_rate_Hz"])
    if asset.metadata:
        if "im_rate_hz" in asset.metadata:
            return float(asset.metadata["im_rate_hz"])
        if "im_rate_Hz" in asset.metadata:
            return float(asset.metadata["im_rate_Hz"])
    raise ValueError("Could not resolve imaging rate. Provide metadata['im_rate_hz'].")


def _resolve_indicator2(asset: SessionAssets, metadata: Dict[str, Any]) -> Optional[str]:
    """Resolve the secondary indicator name for extraction metadata.

    Caller-provided metadata takes precedence over ``asset.metadata``.

    Returns
    -------
    Optional[str]
        Resolved ``indicator2`` value, or ``None`` if unavailable.
    """
    if "indicator2" in metadata:
        return metadata["indicator2"]
    if asset.metadata and "indicator2" in asset.metadata:
        return asset.metadata["indicator2"]
    return None


def _apply_roi_mask_to_array(x: np.ndarray, mask: Optional[np.ndarray]) -> np.ndarray:
    """Apply a boolean ROI mask to event or trace arrays.

    Parameters
    ----------
    x
        Array shaped either ``(n_events, n_rois, n_time)`` or ``(n_rois, n_time)``.
    mask
        Optional boolean mask selecting ROIs to keep.

    Returns
    -------
    np.ndarray
        Masked array with the ROI dimension filtered.

    Raises
    ------
    ValueError
        If ``x`` does not have a supported dimensionality.
    """
    if mask is None:
        return x
    if x.ndim == 3:
        return x[:, mask, :]
    if x.ndim == 2:
        return x[mask, :]
    raise ValueError(f"Unsupported array shape for ROI masking: {x.shape}")


def _time_vectors(windows: EventWindows, im_rate_hz: float) -> Dict[str, np.ndarray]:
    """Construct event-relative time vectors for each stimulus family.

    Parameters
    ----------
    windows
        Pre/post event windows in seconds.
    im_rate_hz
        Imaging rate in hertz.

    Returns
    -------
    dict[str, np.ndarray]
        Time vectors for image, change, and omission windows.
    """
    return {
        "image": np.arange(-windows.image[0], windows.image[1], 1.0 / im_rate_hz),
        "change": np.arange(-windows.change[0], windows.change[1], 1.0 / im_rate_hz),
        "omission": np.arange(-windows.omission[0], windows.omission[1], 1.0 / im_rate_hz),
    }


def _empty_event_array(n_rois: int, n_time: int) -> np.ndarray:
    """Create an empty NaN-filled event tensor.

    Parameters
    ----------
    n_rois
        Number of retained ROIs.
    n_time
        Number of samples in each event-aligned window.

    Returns
    -------
    np.ndarray
        Empty event tensor shaped ``(0, n_rois, n_time)``.
    """
    return np.full((0, n_rois, n_time), np.nan, dtype=float)


def _stack_snippets(snippets: List[np.ndarray], n_rois: int, n_time: int) -> np.ndarray:
    """Stack event snippets or return an empty event tensor.

    Parameters
    ----------
    snippets
        List of per-event arrays shaped ``(n_rois, n_time)``.
    n_rois
        Number of retained ROIs, used when ``snippets`` is empty.
    n_time
        Number of samples per event, used when ``snippets`` is empty.

    Returns
    -------
    np.ndarray
        Event tensor shaped ``(n_events, n_rois, n_time)``.
    """
    if len(snippets) == 0:
        return _empty_event_array(n_rois, n_time)
    return np.stack(snippets, axis=0)


def _build_sequence_output(
    seq_events: Dict[str, Dict[str, Any]],
    ordered_snippets: Dict[int, np.ndarray],
    *,
    n_rois_kept: int,
    n_time: int,
) -> Dict[str, Any]:
    """Summarize change-locked calcium snippets by image sequence position.

    Parameters
    ----------
    seq_events
        Change-locked sequence groups produced by
        :func:`build_change_locked_sequences`.
    ordered_snippets
        Mapping from ordered image-event index to an ROI-by-time snippet.
    n_rois_kept
        Number of ROIs retained after optional QC masking.
    n_time
        Number of samples in each image-aligned snippet.

    Returns
    -------
    dict[str, Any]
        Per-image sequence summaries for prechange, repeated, and terminal image
        positions.
    """
    out: Dict[str, Any] = {}

    for image_name, groups in seq_events.items():
        pre_arrays: List[np.ndarray] = []
        rep_arrays: List[np.ndarray] = []
        term_arrays: List[np.ndarray] = []
        seq_lengths: List[int] = []

        for pre_evts, rep_evts, term_evt in zip(groups["prechange"], groups["repeated"], groups["terminal"]):
            pre_snips = [ordered_snippets.get(evt.event_idx) for evt in pre_evts]
            if all(s is not None for s in pre_snips):
                pre_arrays.append(np.stack(pre_snips, axis=0))

            rep_snips = [ordered_snippets.get(evt.event_idx) for evt in rep_evts]
            rep_snips = [s for s in rep_snips if s is not None]
            if len(rep_snips) > 0:
                rep_arr = np.stack(rep_snips, axis=0)
                rep_arrays.append(rep_arr)
                seq_lengths.append(rep_arr.shape[0])

            t = ordered_snippets.get(term_evt.event_idx)
            if t is not None:
                term_arrays.append(t)

        pre_summary = tolerant_summary_ragged(pre_arrays)
        rep_summary = tolerant_summary_ragged(rep_arrays)
        term_stack = _stack_snippets(term_arrays, n_rois_kept, n_time)
        term_summary = summarize_event_tensor(term_stack)

        out[image_name] = {
            "prechange": {
                **pre_summary,
                "n_sequences": np.array(len(pre_arrays), dtype=int),
                "positions": np.array([-2, -1], dtype=int),
            },
            "repeated": {
                **rep_summary,
                "n_sequences": np.array(len(rep_arrays), dtype=int),
                "sequence_lengths": np.asarray(seq_lengths, dtype=int),
                "positions": np.arange(rep_summary["mean"].shape[0], dtype=int),
            },
            "terminal": {
                **term_summary,
                "n_sequences": np.array(len(term_arrays), dtype=int),
                "position": np.array([999], dtype=int),
            },
        }

    return out

def _has_readable_soma_ca_data(
    exp: GlutamateSummary,
    dmd: int,
    *,
    trace_type: str = "Fsvd",
) -> Tuple[bool, Optional[str]]:
    """
    Check whether this DMD has readable exported manual soma ROI traces.
    """
    try:
        keep = np.asarray(exp.keep_trials[dmd - 1], dtype=bool)
        valid_trials = np.flatnonzero(keep)
        if valid_trials.size == 0:
            return False, "no valid trials"

        last_err: Optional[Exception] = None

        for t0 in valid_trials:
            try:
                x = exp.get_user_roi_traces(
                    dmd=dmd,
                    trial=int(t0) + 1,
                    trace_type=trace_type,
                    squeeze_channels=False,
                )
                x = np.asarray(x)

                if x.ndim in (2, 3) and x.size > 0:
                    return True, None

            except Exception as e:
                last_err = e
                continue

        reason = "no readable manual soma ROI traces in SummaryLoCo"
        if last_err is not None:
            reason += f"; last error={repr(last_err)}"
        return False, reason

    except Exception as e:
        return False, f"failed to inspect soma ROI traces: {repr(e)}"

def _reconstruct_ca_session_traces(
    exp: GlutamateSummary,
    dmd: int,
    *,
    im_rate_hz: float,
    epoch_start_sec: float,
    epoch_end_sec: Optional[float] = None,
    motion_correct: bool = True,
    use_glu: bool = True,
    max_session_minutes=None,
) -> Dict[str, Any]:
    """
    Reconstruct session-wide soma Ca traces by concatenating processed per-trial
    calcium traces in trial order.

    Key differences from the previous implementation:
      - requests per-trial outputs with ``pad_to="none"`` so valid trials keep
        their true processed lengths
      - preserves those true lengths in ``trial_lengths_samples``
      - fills invalid trials with NaN blocks using the median valid-trial length
      - optionally warps the per-sample timebase to the measured imaging epoch,
        which prevents small per-trial rounding errors from accumulating into a
        noticeable global stimulus lag later in the session
    """
    ca_dict = exp.get_processed_soma_ca_all_trials(
        dmd=dmd,
        fs_hz=im_rate_hz,
        pad_to="none",
        include_invalid=True,
        motion_correct=motion_correct,
        use_glu_as_motion_regressor=use_glu,
        max_session_minutes=max_session_minutes,
    )

    if ca_dict is None:
        return {
            "traces": np.empty((0, 0), dtype=float),
            "trial_valid_mask": np.zeros((0,), dtype=bool),
            "trial_lengths_samples": np.zeros((0,), dtype=int),
            "trial_starts_sec": np.zeros((0,), dtype=float),
            "session_start_sec": float(epoch_start_sec),
            "timebase_sec": np.empty((0,), dtype=float),
            "nominal_timebase_sec": np.empty((0,), dtype=float),
            "reconstructed_duration_sec": 0.0,
            "nominal_reconstructed_duration_sec": 0.0,
            "timebase_mode": "empty",
            "effective_im_rate_hz": float(im_rate_hz),
            "duration_vs_epoch_error_sec": np.nan,
        }

    if "dff" not in ca_dict:
        raise KeyError(
            "get_processed_soma_ca_all_trials(...) did not return key 'dff'. "
            f"Available keys: {list(ca_dict.keys())}"
        )

    dff_trials = ca_dict["dff"]
    if isinstance(dff_trials, np.ndarray):
        if dff_trials.ndim != 3:
            raise ValueError(
                f"Expected Ca dff shape (n_trials, n_rois, n_samples), got {dff_trials.shape}"
            )
        trial_list: List[Optional[np.ndarray]] = [np.asarray(dff_trials[i], dtype=float) for i in range(dff_trials.shape[0])]
    else:
        trial_list = []
        for tr in list(dff_trials):
            if tr is None:
                trial_list.append(None)
            else:
                arr = np.asarray(tr, dtype=float)
                if arr.ndim != 2:
                    raise ValueError(
                        "Expected per-trial processed Ca arrays shaped (n_rois, n_samples); "
                        f"got {arr.shape}."
                    )
                trial_list.append(arr)

    n_trials = len(trial_list)
    if n_trials == 0:
        return {
            "traces": np.empty((0, 0), dtype=float),
            "trial_valid_mask": np.zeros((0,), dtype=bool),
            "trial_lengths_samples": np.zeros((0,), dtype=int),
            "trial_starts_sec": np.zeros((0,), dtype=float),
            "session_start_sec": float(epoch_start_sec),
            "timebase_sec": np.empty((0,), dtype=float),
            "nominal_timebase_sec": np.empty((0,), dtype=float),
            "reconstructed_duration_sec": 0.0,
            "nominal_reconstructed_duration_sec": 0.0,
            "timebase_mode": "empty",
            "effective_im_rate_hz": float(im_rate_hz),
            "duration_vs_epoch_error_sec": np.nan,
        }

    valid_trials = [arr for arr in trial_list if arr is not None and arr.ndim == 2 and arr.size > 0]
    if len(valid_trials) == 0:
        return {
            "traces": np.empty((0, 0), dtype=float),
            "trial_valid_mask": np.zeros((n_trials,), dtype=bool),
            "trial_lengths_samples": np.zeros((n_trials,), dtype=int),
            "trial_starts_sec": np.zeros((n_trials,), dtype=float),
            "session_start_sec": float(epoch_start_sec),
            "timebase_sec": np.empty((0,), dtype=float),
            "nominal_timebase_sec": np.empty((0,), dtype=float),
            "reconstructed_duration_sec": 0.0,
            "nominal_reconstructed_duration_sec": 0.0,
            "timebase_mode": "no_valid_trials",
            "effective_im_rate_hz": float(im_rate_hz),
            "duration_vs_epoch_error_sec": np.nan,
        }

    n_rois = int(max(arr.shape[0] for arr in valid_trials))
    valid_lengths = np.asarray([arr.shape[1] for arr in valid_trials], dtype=int)
    invalid_fill_length = int(np.median(valid_lengths)) if valid_lengths.size else 0

    trial_lengths = np.zeros((n_trials,), dtype=int)
    trial_valid_mask = np.zeros((n_trials,), dtype=bool)
    for i, arr in enumerate(trial_list):
        if arr is None:
            trial_lengths[i] = invalid_fill_length
            continue
        trial_lengths[i] = int(arr.shape[1])
        trial_valid_mask[i] = np.isfinite(arr).any()

    total_samples = int(np.sum(trial_lengths))
    if n_rois == 0 or total_samples == 0:
        return {
            "traces": np.empty((0, 0), dtype=float),
            "trial_valid_mask": trial_valid_mask,
            "trial_lengths_samples": trial_lengths,
            "trial_starts_sec": np.zeros((n_trials,), dtype=float),
            "session_start_sec": float(epoch_start_sec),
            "timebase_sec": np.empty((0,), dtype=float),
            "nominal_timebase_sec": np.empty((0,), dtype=float),
            "reconstructed_duration_sec": 0.0,
            "nominal_reconstructed_duration_sec": 0.0,
            "timebase_mode": "empty",
            "effective_im_rate_hz": float(im_rate_hz),
            "duration_vs_epoch_error_sec": np.nan,
        }

    traces = np.full((n_rois, total_samples), np.nan, dtype=float)
    trial_starts_sec = np.zeros((n_trials,), dtype=float)

    pos = 0
    for i, arr in enumerate(trial_list):
        L = int(trial_lengths[i])
        trial_starts_sec[i] = float(epoch_start_sec + pos / float(im_rate_hz))
        if arr is not None and L > 0:
            rcopy = min(n_rois, arr.shape[0])
            tcopy = min(L, arr.shape[1])
            traces[:rcopy, pos:pos + tcopy] = arr[:rcopy, :tcopy]
        pos += L

    nominal_timebase_sec = epoch_start_sec + np.arange(total_samples, dtype=float) / float(im_rate_hz)
    nominal_span_sec = float((total_samples - 1) / float(im_rate_hz)) if total_samples > 1 else 0.0

    timebase_mode = "nominal_fixed_rate"
    timebase_sec = nominal_timebase_sec.copy()
    effective_im_rate_hz = float(im_rate_hz)
    duration_vs_epoch_error_sec = np.nan

    if epoch_end_sec is not None and np.isfinite(epoch_end_sec) and total_samples > 1:
        epoch_span_sec = float(epoch_end_sec - epoch_start_sec)
        if epoch_span_sec > 0:
            timebase_sec = np.linspace(
                float(epoch_start_sec),
                float(epoch_end_sec),
                int(total_samples),
                endpoint=True,
                dtype=float,
            )
            timebase_mode = "epoch_warped_linear"
            effective_im_rate_hz = float((total_samples - 1) / epoch_span_sec)
            duration_vs_epoch_error_sec = float(nominal_span_sec - epoch_span_sec)

    reconstructed_duration_sec = float(timebase_sec[-1] - timebase_sec[0]) if total_samples > 1 else 0.0

    return {
        "traces": traces,
        "trial_valid_mask": trial_valid_mask,
        "trial_lengths_samples": trial_lengths,
        "trial_starts_sec": trial_starts_sec,
        "session_start_sec": float(epoch_start_sec),
        "timebase_sec": timebase_sec,
        "nominal_timebase_sec": nominal_timebase_sec,
        "reconstructed_duration_sec": reconstructed_duration_sec,
        "nominal_reconstructed_duration_sec": nominal_span_sec,
        "timebase_mode": timebase_mode,
        "effective_im_rate_hz": effective_im_rate_hz,
        "duration_vs_epoch_error_sec": duration_vs_epoch_error_sec,
    }


def _nearest_timebase_index(bundle: Dict[str, Any], onset_sec: float, *, im_rate_hz: float) -> int:
    """Find the sample index nearest to a stimulus onset.

    The function prefers an explicit per-sample timebase when present in the bundle
    and falls back to fixed-rate indexing from the session start otherwise.

    Parameters
    ----------
    bundle
        Reconstructed calcium trace bundle from :func:`_reconstruct_ca_session_traces`.
    onset_sec
        Stimulus onset time in corrected HARP seconds.
    im_rate_hz
        Nominal imaging rate used for fallback indexing.

    Returns
    -------
    int
        Nearest valid sample index in the reconstructed trace.
    """
    traces = np.asarray(bundle["traces"], dtype=float)
    n_total = int(traces.shape[1]) if traces.ndim == 2 else 0
    if n_total == 0:
        return 0

    tb = np.asarray(bundle.get("timebase_sec", []), dtype=float).reshape(-1)
    if tb.size == n_total and np.all(np.isfinite(tb)) and np.all(np.diff(tb) > 0):
        idx = int(np.searchsorted(tb, float(onset_sec), side="left"))
        if idx <= 0:
            return 0
        if idx >= n_total:
            return n_total - 1
        prev_idx = idx - 1
        if abs(float(tb[idx]) - float(onset_sec)) < abs(float(onset_sec) - float(tb[prev_idx])):
            return idx
        return prev_idx

    center = int(round((float(onset_sec) - float(bundle["session_start_sec"])) * float(im_rate_hz)))
    return max(0, min(center, n_total - 1))


def process_calcium_extraction(
    asset: SessionAssets,
    *,
    metadata: Optional[Dict[str, Any]] = None,
    use_soma_qc: bool = True,
    motion_correct: bool = True,
    use_glu: bool = True,
    max_session_minutes=None,
    overwrite: bool = False,
) -> Dict[str, Any]:
    """Extract event-aligned soma calcium datasets for one session.

    This function loads corrected stimulus events and imaging epochs, reconstructs
    continuous DMD-specific calcium traces, optionally applies soma-QC masks, aligns
    traces to image/change/omission events, constructs change-locked image sequence
    summaries, and writes compressed NPZ packages plus extraction metadata.

    Parameters
    ----------
    asset
        Session asset bundle with SummaryLoCo, behavior log, QC, and derived paths.
    metadata
        Optional session metadata, including imaging rate and pre/post windows.
    use_soma_qc
        Apply ``valid_soma_rois_dmd*.npy`` masks when available.
    motion_correct
        Request motion-corrected calcium traces from SummaryLoCo processing.
    use_glu
        Use glutamate as a motion regressor during calcium trace reconstruction.
    max_session_minutes
        Optional cap on the amount of session data reconstructed.
    overwrite
        Recompute outputs even if all expected files already exist.

    Returns
    -------
    dict[str, Any]
        Status and output paths for mean, single-trial, sequence, and metadata
        artifacts.
    """
    metadata = metadata or {}
    pp = metadata.get("prepost_sec", {})
    windows = EventWindows(
        image=tuple(pp.get("image", pp.get("image_identity", (0.25, 0.50)))),
        change=tuple(pp.get("change", (1.00, 0.75))),
        omission=tuple(pp.get("omission", (1.00, 1.50))),
    )
    im_rate_hz = _resolve_im_rate_hz(asset, metadata)
    indicator2 = _resolve_indicator2(asset, metadata)

    if asset.summary_mat is None:
        raise FileNotFoundError("asset.summary_mat is missing")
    if asset.bonsai_event_log_csv is None:
        raise FileNotFoundError("asset.bonsai_event_log_csv is missing")
    if asset.qc_dir is None or asset.derived_dir is None:
        raise ValueError("asset.qc_dir and asset.derived_dir must be set")

    cal_dir = Path(asset.derived_dir) / "calcium"
    cal_qc_dir = Path(asset.qc_dir) / "calcium"
    cal_dir.mkdir(parents=True, exist_ok=True)
    cal_qc_dir.mkdir(parents=True, exist_ok=True)

    mean_npz = cal_dir / "calcium_mean_dff.npz"
    single_npz = cal_dir / "calcium_single_trial_dff.npz"
    seq_npz = cal_dir / "calcium_sequence_dff.npz"
    meta_json = cal_qc_dir / "calcium_extraction_meta.json"

    if all(p.exists() for p in [mean_npz, single_npz, seq_npz, meta_json]) and not overwrite:
        return {
            "status": "exists",
            "mean_npz": str(mean_npz),
            "single_npz": str(single_npz),
            "seq_npz": str(seq_npz),
            "meta_json": str(meta_json),
        }

    stim_df = load_corrected_bonsai_csv(asset.bonsai_event_log_csv)
    epoch_df = load_imaging_epochs_csv(Path(asset.qc_dir) / "behavior" / "imaging_epochs.csv")
    epoch_start_sec = float(epoch_df.iloc[0]["start_time"])
    epoch_end_sec = float(epoch_df.iloc[-1]["end_time"])
    epoch_duration_sec = float(epoch_end_sec - epoch_start_sec)

    image_times, ordered_images = extract_image_intervals(stim_df)
    change_times = extract_change_intervals(stim_df)
    omission_times = extract_omission_intervals(stim_df)
    extract_ordered_change_targets(stim_df, ordered_images)

    image_times_f = filter_intervals_to_epochs(image_times, epoch_df, pre_time=windows.image[0], post_time=windows.image[1])
    change_times_f = filter_intervals_to_epochs(change_times, epoch_df, pre_time=windows.change[0], post_time=windows.change[1])
    omission_times_f = filter_intervals_to_epochs(omission_times, epoch_df, pre_time=windows.omission[0], post_time=windows.omission[1])
    ordered_images_f = filter_ordered_images_to_epochs(ordered_images, epoch_df, pre_time=windows.image[0], post_time=windows.image[1])

    exp = GlutamateSummary(asset.summary_mat)
    tvecs = _time_vectors(windows, im_rate_hz)

    base_meta = {
        "schema_version": "0.1.2",
        "session_id": asset.session_id,
        "subject_id": int(asset.subject_id),
        "summary_mat": str(asset.summary_mat),
        "bonsai_event_log_csv": str(asset.bonsai_event_log_csv),
        "indicator2": indicator2,
        "im_rate_hz": float(im_rate_hz),
        "windows_sec": {
            "image": tuple(float(x) for x in windows.image),
            "change": tuple(float(x) for x in windows.change),
            "omission": tuple(float(x) for x in windows.omission),
        },
        "use_soma_qc": bool(use_soma_qc),
        "motion_correct": bool(motion_correct),
        "epoch_start_sec": epoch_start_sec,
        "epoch_end_sec": epoch_end_sec,
    }

    mean_pkg: Dict[str, Any] = {"metadata": base_meta, "timebase_sec": tvecs, "DMD1": {}, "DMD2": {}}
    single_pkg: Dict[str, Any] = {"metadata": base_meta, "timebase_sec": tvecs, "DMD1": {}, "DMD2": {}}
    seq_pkg: Dict[str, Any] = {"metadata": base_meta, "timebase_sec": {"image": tvecs["image"]}, "DMD1": {}, "DMD2": {}}

    meta_out: Dict[str, Any] = {
        "schema_version": "0.1.2",
        "session_id": asset.session_id,
        "indicator2": indicator2,
        "motion_correct": bool(motion_correct),
        "use_soma_qc": bool(use_soma_qc),
        "windows_sec": base_meta["windows_sec"],
        "event_counts": {
            "image_total": int(sum(len(v) for v in image_times.values())),
            "image_after_epoch_filter": int(sum(len(v) for v in image_times_f.values())),
            "change_total": int(len(change_times)),
            "change_after_epoch_filter": int(len(change_times_f)),
            "omission_total": int(len(omission_times)),
            "omission_after_epoch_filter": int(len(omission_times_f)),
            "n_unique_image_ids_total": int(len(image_times)),
            "n_unique_image_ids_after_epoch_filter": int(len(image_times_f)),
        },
        "epoch_duration_sec": epoch_duration_sec,
        "per_dmd": {},
    }

    seq_events = build_change_locked_sequences(ordered_images_f)

    for dmd in (1, 2):
        has_soma_data, missing_reason = _has_readable_soma_ca_data(exp, dmd=dmd, trace_type="Fsvd")
        if not has_soma_data:
            meta_out["per_dmd"][f"DMD{dmd}"] = {
                "skipped": True,
                "reason": missing_reason,
            }
            continue

        bundle = _reconstruct_ca_session_traces(
            exp,
            dmd=dmd,
            im_rate_hz=im_rate_hz,
            epoch_start_sec=epoch_start_sec,
            epoch_end_sec=epoch_end_sec,
            motion_correct=motion_correct,
            use_glu=use_glu,
            max_session_minutes=max_session_minutes,
        )
        if bundle["traces"].size == 0:
            meta_out["per_dmd"][f"DMD{dmd}"] = {"skipped": True, "reason": "no calcium traces"}
            continue

        roi_mask = None
        if use_soma_qc:
            p = cal_qc_dir / f"valid_soma_rois_dmd{dmd}.npy"
            if p.exists():
                roi_mask = np.load(p)

        n_rois_total = int(bundle["traces"].shape[0])
        if roi_mask is None:
            roi_mask = np.ones((n_rois_total,), dtype=bool)
        n_rois_kept = int(np.sum(roi_mask))
        roi_ids = np.array([f"DMD{dmd}_roi{i:04d}" for i in range(n_rois_total)])[roi_mask]

        aligned_images, image_onsets = align_traces_to_session_intervals(
            bundle,
            image_times_f,
            im_rate_hz=im_rate_hz,
            pre_time=windows.image[0],
            post_time=windows.image[1],
        )

        aligned_changes, change_onsets = align_traces_to_session_intervals(
            bundle,
            change_times_f,
            im_rate_hz=im_rate_hz,
            pre_time=windows.change[0],
            post_time=windows.change[1],
        )

        aligned_omissions, omission_onsets = align_traces_to_session_intervals(
            bundle,
            omission_times_f,
            im_rate_hz=im_rate_hz,
            pre_time=windows.omission[0],
            post_time=windows.omission[1],
        )

        aligned_images = {k: _apply_roi_mask_to_array(v, roi_mask) for k, v in aligned_images.items()}
        aligned_changes = _apply_roi_mask_to_array(aligned_changes, roi_mask)
        aligned_omissions = _apply_roi_mask_to_array(aligned_omissions, roi_mask)

        ordered_snippets: Dict[int, np.ndarray] = {}
        n_img_time = len(tvecs["image"])
        for evt in ordered_images_f:
            center = _nearest_timebase_index(bundle, float(evt.onset), im_rate_hz=im_rate_hz)
            n_pre = int(round(windows.image[0] * im_rate_hz))
            start = center - n_pre
            stop = start + n_img_time
            if start < 0 or stop > bundle["traces"].shape[1]:
                continue
            ordered_snippets[evt.event_idx] = _apply_roi_mask_to_array(bundle["traces"][:, start:stop], roi_mask)

        mean_pkg[f"DMD{dmd}"]["image_identity"] = {
            img: summarize_event_tensor(arr) for img, arr in aligned_images.items()
        }
        mean_pkg[f"DMD{dmd}"]["change"] = summarize_event_tensor(aligned_changes)
        mean_pkg[f"DMD{dmd}"]["omission"] = summarize_event_tensor(aligned_omissions)
        mean_pkg[f"DMD{dmd}"]["roi_ids"] = roi_ids
        mean_pkg[f"DMD{dmd}"]["valid_rois_mask"] = roi_mask

        single_pkg[f"DMD{dmd}"]["image_identity"] = aligned_images
        single_pkg[f"DMD{dmd}"]["change"] = aligned_changes
        single_pkg[f"DMD{dmd}"]["omission"] = aligned_omissions
        single_pkg[f"DMD{dmd}"]["roi_ids"] = roi_ids
        single_pkg[f"DMD{dmd}"]["valid_rois_mask"] = roi_mask

        seq_pkg[f"DMD{dmd}"]["image_identity"] = _build_sequence_output(
            seq_events,
            ordered_snippets,
            n_rois_kept=n_rois_kept,
            n_time=n_img_time,
        )
        seq_pkg[f"DMD{dmd}"]["roi_ids"] = roi_ids
        seq_pkg[f"DMD{dmd}"]["valid_rois_mask"] = roi_mask

        image_count_by_id = {img: int(arr.shape[0]) for img, arr in aligned_images.items()}
        zero_count_ids = [img for img, cnt in image_count_by_id.items() if cnt == 0]

        meta_out["per_dmd"][f"DMD{dmd}"] = {
            "skipped": False,
            "n_rois_total": n_rois_total,
            "n_rois_kept": n_rois_kept,
            "n_trials_total": int(len(bundle["trial_valid_mask"])),
            "n_trials_valid": int(np.sum(bundle["trial_valid_mask"])),
            "n_trials_invalid": int(np.sum(~bundle["trial_valid_mask"])),
            "trial_lengths_samples": bundle["trial_lengths_samples"].tolist(),
            "timebase_mode": bundle.get("timebase_mode", "unknown"),
            "effective_im_rate_hz": float(bundle.get("effective_im_rate_hz", im_rate_hz)),
            "reconstructed_duration_sec": float(bundle["reconstructed_duration_sec"]),
            "nominal_reconstructed_duration_sec": float(bundle.get("nominal_reconstructed_duration_sec", bundle["reconstructed_duration_sec"])),
            "duration_vs_epoch_error_sec": float(bundle.get("duration_vs_epoch_error_sec", np.nan)),
            "n_image_ids_extracted": int(len(image_count_by_id)),
            "image_count_by_id": image_count_by_id,
            "zero_count_image_ids": zero_count_ids,
            "n_change_events_extracted": int(aligned_changes.shape[0]),
            "n_omission_events_extracted": int(aligned_omissions.shape[0]),
            "sequence_counts_by_id": {
                img: {
                    "n_prechange_sequences": int(seq_pkg[f"DMD{dmd}"]["image_identity"][img]["prechange"]["n_sequences"]),
                    "n_repeated_sequences": int(seq_pkg[f"DMD{dmd}"]["image_identity"][img]["repeated"]["n_sequences"]),
                    "n_terminal_sequences": int(seq_pkg[f"DMD{dmd}"]["image_identity"][img]["terminal"]["n_sequences"]),
                }
                for img in seq_pkg[f"DMD{dmd}"]["image_identity"].keys()
            },
        }

    np.savez_compressed(mean_npz, data=np.array([mean_pkg], dtype=object))
    np.savez_compressed(single_npz, data=np.array([single_pkg], dtype=object))
    np.savez_compressed(seq_npz, data=np.array([seq_pkg], dtype=object))

    with open(meta_json, "w") as f:
        json.dump(meta_out, f, indent=2)

    return {
        "status": "ok",
        "mean_npz": str(mean_npz),
        "single_npz": str(single_npz),
        "seq_npz": str(seq_npz),
        "meta_json": str(meta_json),
    }